// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';

List users = [
  {
    'userId': 0,
    'title': "Rishab",
    'date': "01-03-2022",
    "email": "abc@gmail.com",
    "phoneNo": "123456789",
    "callsMade": "123",
    "lastActive": "today",
    "packages": [
      {
        "id": 1,
        "name": "Subscription 1",
        "desc": "Lorem Ipsum",
        "purchasedCount": "1234",
        "img": "assets/icons/xd_file.svg",
        'date': "01-03-2022",
        "status": "pending",
      },
      {
        "id": 2,
        "name": "Subscription 2",
        "purchasedCount": "1234",
        "img": "assets/icons/Figma_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "recieved",
      },
      {
        "id": 3,
        "name": "Subscription 3",
        "purchasedCount": "1234",
        "img": "assets/icons/doc_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "shipped",
      },
    ],
    'icon': Icon(
      Icons.arrow_forward,
      color: Colors.blue,
    ),
  },
  {
    'userId': 1,
    'title': "John",
    'date': "01-03-2022",
    "email": "abc@gmail.com",
    "phoneNo": "123456789",
    "callsMade": "123",
    "lastActive": "today",
    "packages": [
      {
        "id": 1,
        "name": "Subscription 1",
        "desc": "Lorem Ipsum",
        "purchasedCount": "1234",
        "img": "assets/icons/xd_file.svg",
        'date': "01-03-2022",
        "status": "pending",
      },
      {
        "id": 2,
        "name": "Subscription 2",
        "purchasedCount": "1234",
        "img": "assets/icons/Figma_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "recieved",
      },
      {
        "id": 3,
        "name": "Subscription 3",
        "purchasedCount": "1234",
        "img": "assets/icons/doc_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "shipped",
      },
    ],
    'icon': Icon(
      Icons.arrow_forward,
      color: Colors.blue,
    ),
  },
  {
    'userId': 2,
    'title': "Jane",
    'date': "01-03-2022",
    "email": "abc@gmail.com",
    "phoneNo": "123456789",
    "callsMade": "123",
    "lastActive": "yeaterday",
    "packages": [
      {
        "id": 1,
        "name": "Subscription 1",
        "desc": "Lorem Ipsum",
        "purchasedCount": "1234",
        "img": "assets/icons/xd_file.svg",
        'date': "01-03-2022",
        "status": "pending",
      },
      {
        "id": 2,
        "name": "Subscription 2",
        "purchasedCount": "1234",
        "img": "assets/icons/Figma_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "recieved",
      },
      {
        "id": 3,
        "name": "Subscription 3",
        "purchasedCount": "1234",
        "img": "assets/icons/doc_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "shipped",
      },
    ],
    'icon': Icon(
      Icons.arrow_forward,
      color: Colors.blue,
    ),
  },
  {
    'userId': 3,
    'title': "Michael",
    'date': "01-03-2022",
    "email": "abc@gmail.com",
    "phoneNo": "123456789",
    "callsMade": "123",
    "lastActive": "2 days ago",
    "packages": [
      {
        "id": 1,
        "name": "Subscription 1",
        "desc": "Lorem Ipsum",
        "purchasedCount": "1234",
        "img": "assets/icons/xd_file.svg",
        'date': "01-03-2022",
        "status": "pending",
      },
      {
        "id": 2,
        "name": "Subscription 2",
        "purchasedCount": "1234",
        "img": "assets/icons/Figma_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "recieved",
      },
      {
        "id": 3,
        "name": "Subscription 3",
        "purchasedCount": "1234",
        "img": "assets/icons/doc_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "shipped",
      },
    ],
    'icon': Icon(
      Icons.arrow_forward,
      color: Colors.blue,
    ),
  },
  {
    'userId': 4,
    'title': "James",
    'date': "01-03-2022",
    "email": "abc@gmail.com",
    "phoneNo": "123456789",
    "callsMade": "123",
    "lastActive": "today",
    "packages": [
      {
        "id": 1,
        "name": "Subscription 1",
        "desc": "Lorem Ipsum",
        "purchasedCount": "1234",
        "img": "assets/icons/xd_file.svg",
        'date': "01-03-2022",
        "status": "pending",
      },
      {
        "id": 2,
        "name": "Subscription 2",
        "purchasedCount": "1234",
        "img": "assets/icons/Figma_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "recieved",
      },
      {
        "id": 3,
        "name": "Subscription 3",
        "purchasedCount": "1234",
        "img": "assets/icons/doc_file.svg",
        'date': "01-03-2022",
        "desc": "Lorem Ipsum",
        "status": "shipped",
      },
    ],
    'icon': Icon(
      Icons.arrow_forward,
      color: Colors.blue,
    ),
  },
];
